#!/bin/bash

currentDirectory=$(pwd)
if [ $# -eq 0 ]; then
  base_directory=/workspace/bullhorn/bh-env/novo-dev/novo
else
  base_directory=$1
fi

function gitoperations {
  echo "STARTING GIT OPERATIONS"
  current_branch=$(git symbolic-ref --short -q HEAD)
  merged_branches=$(git branch --merged | grep -v master | grep -v development)
  echo "Current Branch: $current_branch"
  git remote prune origin
  git up
  if [[ $merged_branches == *"$current_branch"* || $current_branch == "development" ]]; then
    if [[ `git branch` == *"development"*  ]]; then
      echo "Checking out development"
      git checkout development
    else
      "Checking out master"
      git checkout master
    fi
  fi
  echo "Merged branches: $merged_branches"
  #git branch -d $merged_branches 
}

function run_npm {
  echo "Check for package.json in current directory"
  if [[ -f "package.json" ]]; then
    echo "Running npm install and npm update"
    npm install
    npm update
  else
    echo "No damn file to make me run NPM INSTALL!!!!!!!!!!!!!!!!!"
  fi
}

cd $base_directory
git up
run_npm
for git_dir in `find . -type d -name .git | xargs -n 1 dirname`; do
  cd $git_dir
  echo "********** I'm in $(pwd)"
  gitoperations 
  run_npm
  cd $base_directory
done

cd $currentDirectory
